// src/components/LandingPage/LandingPage.jsx
import React from "react";
import { Link } from "react-router-dom";
import {
  Dumbbell,
  Brain,
  Heart,
  Target,
  Users,
  Sparkles,
  ArrowRight,
  CheckCircle,
  Award,
  Zap,
  Shield,
  TrendingUp,
} from "lucide-react";

const LandingPage = () => {
  const features = [
    {
      icon: <Brain className="w-8 h-8 text-purple-400" />,
      title: "AI-Powered Plans",
      description:
        "Get personalized workout and diet plans generated by our advanced AI algorithms",
      color: "from-purple-900/30 to-pink-900/30",
    },
    {
      icon: <Target className="w-8 h-8 text-blue-400" />,
      title: "Smart Tracking",
      description:
        "Track your progress with intelligent analytics and predictive insights",
      color: "from-blue-900/30 to-cyan-900/30",
    },
    {
      icon: <Users className="w-8 h-8 text-green-400" />,
      title: "Expert Trainers",
      description:
        "Connect with certified trainers for 1-on-1 coaching sessions",
      color: "from-green-900/30 to-emerald-900/30",
    },
    {
      icon: <Award className="w-8 h-8 text-yellow-400" />,
      title: "Achievement System",
      description:
        "Earn badges and rewards as you reach your fitness milestones",
      color: "from-yellow-900/30 to-orange-900/30",
    },
  ];

  const stats = [
    { number: "10K+", label: "Active Members", icon: "👥" },
    { number: "500+", label: "Workout Plans", icon: "💪" },
    { number: "200+", label: "Diet Plans", icon: "🥗" },
    { number: "50+", label: "Expert Trainers", icon: "👨‍🏫" },
  ];

  return (
    <div className="min-h-screen bg-black text-white overflow-hidden">
      {/* Hero Section */}
      <section className="relative min-h-screen flex items-center justify-center px-4">
        {/* Background Effects */}
        <div className="absolute inset-0 overflow-hidden">
          <div className="absolute top-1/4 left-1/4 w-96 h-96 bg-purple-600/10 rounded-full blur-3xl"></div>
          <div className="absolute bottom-1/4 right-1/4 w-96 h-96 bg-blue-600/10 rounded-full blur-3xl"></div>
          <div className="absolute top-3/4 left-1/3 w-64 h-64 bg-pink-600/10 rounded-full blur-3xl"></div>
        </div>

        <div className="relative z-10 max-w-7xl mx-auto">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-center">
            {/* Left Column - Content */}
            <div className="text-center lg:text-left">
              {/* Badge */}
              <div className="inline-flex items-center gap-2 px-4 py-2 bg-linear-to-r from-purple-900/30 to-pink-900/30 border border-purple-700/30 rounded-full mb-6">
                <Sparkles className="w-4 h-4 text-yellow-400" />
                <span className="text-sm">AI-Powered Fitness Revolution</span>
              </div>

              {/* Main Heading */}
              <h1 className="text-5xl md:text-7xl font-bold mb-6 leading-tight">
                Transform Your{" "}
                <span className="text-transparent bg-clip-text bg-linear-to-r from-purple-400 via-pink-400 to-blue-400">
                  Fitness Journey
                </span>{" "}
                with AI
              </h1>

              {/* Subtitle */}
              <p className="text-xl text-gray-400 mb-8 max-w-2xl">
                FitAI combines artificial intelligence with expert fitness
                knowledge to deliver personalized workout plans, nutrition
                guidance, and progress tracking.
              </p>

              {/* CTA Buttons */}
              <div className="flex flex-col sm:flex-row gap-4 mb-12">
                <Link
                  to="/login"
                  className="group px-8 py-4 bg-linear-to-r from-purple-600 to-pink-600 rounded-xl hover:from-purple-700 hover:to-pink-700 transition-all duration-300 transform hover:scale-[1.02] shadow-lg shadow-purple-500/20 flex items-center justify-center gap-3"
                >
                  <span className="text-lg font-semibold">
                    Start Your Journey
                  </span>
                  <ArrowRight className="w-5 h-5 group-hover:translate-x-1 transition-transform" />
                </Link>
                <Link
                  to="/signup"
                  className="px-8 py-4 bg-gray-900 border border-gray-800 rounded-xl hover:bg-gray-800 transition-all duration-300 transform hover:scale-[1.02] flex items-center justify-center gap-3"
                >
                  <span className="text-lg font-semibold">Join as Trainer</span>
                  <Award className="w-5 h-5 text-blue-400" />
                </Link>
              </div>

              {/* Stats */}
              <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
                {stats.map((stat, index) => (
                  <div key={index} className="text-center">
                    <div className="text-2xl md:text-3xl font-bold mb-1">
                      {stat.number}
                    </div>
                    <div className="text-sm text-gray-400">{stat.label}</div>
                  </div>
                ))}
              </div>
            </div>

            {/* Right Column - Visual */}
            <div className="relative">
              <div className="relative bg-linear-to-br from-gray-900 to-black rounded-3xl p-8 border border-gray-800 shadow-2xl">
                {/* Floating Elements */}
                <div className="absolute -top-6 -left-6 w-24 h-24 bg-linear-to-r from-purple-600 to-pink-600 rounded-2xl flex items-center justify-center">
                  <Dumbbell className="w-12 h-12 text-white" />
                </div>

                <div className="absolute -bottom-6 -right-6 w-20 h-20 bg-linear-to-r from-blue-600 to-cyan-600 rounded-2xl flex items-center justify-center">
                  <Heart className="w-10 h-10 text-white" />
                </div>

                {/* Main Card Content */}
                <div className="relative z-10">
                  <div className="space-y-6">
                    <div className="bg-gray-800/50 rounded-xl p-6 border border-gray-700">
                      <div className="flex items-center gap-3 mb-3">
                        <div className="p-2 bg-linear-to-r from-purple-600 to-pink-600 rounded-lg">
                          <Zap className="w-5 h-5" />
                        </div>
                        <h3 className="text-xl font-bold">
                          AI Workout Generator
                        </h3>
                      </div>
                      <p className="text-gray-400">
                        Get personalized workouts based on your goals, fitness
                        level, and available equipment.
                      </p>
                    </div>

                    <div className="bg-gray-800/50 rounded-xl p-6 border border-gray-700">
                      <div className="flex items-center gap-3 mb-3">
                        <div className="p-2 bg-linear-to-r from-green-600 to-emerald-600 rounded-lg">
                          <Target className="w-5 h-5" />
                        </div>
                        <h3 className="text-xl font-bold">
                          Smart Progress Tracking
                        </h3>
                      </div>
                      <p className="text-gray-400">
                        Track your fitness journey with detailed analytics and
                        predictive insights.
                      </p>
                    </div>

                    <div className="bg-gray-800/50 rounded-xl p-6 border border-gray-700">
                      <div className="flex items-center gap-3 mb-3">
                        <div className="p-2 bg-linear-to-r from-blue-600 to-cyan-600 rounded-lg">
                          <Shield className="w-5 h-5" />
                        </div>
                        <h3 className="text-xl font-bold">Expert Guidance</h3>
                      </div>
                      <p className="text-gray-400">
                        Access certified trainers and nutritionists for
                        personalized coaching.
                      </p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* Scroll Indicator */}
        <div className="absolute bottom-8 left-1/2 transform -translate-x-1/2 animate-bounce">
          <div className="w-6 h-10 border-2 border-gray-600 rounded-full flex justify-center">
            <div className="w-1 h-3 bg-gray-400 rounded-full mt-2"></div>
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="py-20 px-4">
        <div className="max-w-7xl mx-auto">
          <div className="text-center mb-16">
            <h2 className="text-4xl md:text-5xl font-bold mb-4">
              Why Choose{" "}
              <span className="text-transparent bg-clip-text bg-linear-to-r from-purple-400 to-pink-400">
                FitAI
              </span>
            </h2>
            <p className="text-xl text-gray-400 max-w-3xl mx-auto">
              Our platform combines cutting-edge technology with fitness
              expertise to deliver results
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
            {features.map((feature, index) => (
              <div
                key={index}
                className={`bg-linear-to-br ${feature.color} rounded-2xl p-6 border border-gray-800 hover:border-purple-500/30 transition-all duration-300 transform hover:scale-[1.02]`}
              >
                <div className="mb-4">{feature.icon}</div>
                <h3 className="text-xl font-bold mb-3">{feature.title}</h3>
                <p className="text-gray-300">{feature.description}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* How It Works */}
      <section className="py-20 px-4 bg-linear-to-b from-black to-gray-900">
        <div className="max-w-7xl mx-auto">
          <div className="text-center mb-16">
            <h2 className="text-4xl md:text-5xl font-bold mb-4">
              How It{" "}
              <span className="text-transparent bg-clip-text bg-linear-to-r from-blue-400 to-cyan-400">
                Works
              </span>
            </h2>
            <p className="text-xl text-gray-400 max-w-3xl mx-auto">
              Start your fitness transformation in just 3 simple steps
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            {[
              {
                step: "01",
                title: "Create Your Profile",
                description:
                  "Tell us about your goals, fitness level, and preferences",
                icon: "👤",
                color: "from-purple-600 to-pink-600",
              },
              {
                step: "02",
                title: "Get AI Recommendations",
                description: "Receive personalized workout and nutrition plans",
                icon: "🤖",
                color: "from-blue-600 to-cyan-600",
              },
              {
                step: "03",
                title: "Track & Improve",
                description: "Monitor progress and get adaptive plan updates",
                icon: "📈",
                color: "from-green-600 to-emerald-600",
              },
            ].map((item, index) => (
              <div key={index} className="relative">
                <div className="bg-gray-900/50 rounded-2xl p-8 border border-gray-800">
                  <div
                    className={`absolute -top-4 -left-4 w-16 h-16 bg-linear-to-r ${item.color} rounded-2xl flex items-center justify-center text-2xl`}
                  >
                    {item.step}
                  </div>
                  <div className="text-5xl mb-4">{item.icon}</div>
                  <h3 className="text-2xl font-bold mb-3">{item.title}</h3>
                  <p className="text-gray-400">{item.description}</p>
                </div>
                {index < 2 && (
                  <div className="hidden md:block absolute top-1/2 -right-4 w-8 h-0.5 bg-linear-to-r from-purple-600 to-pink-600"></div>
                )}
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-20 px-4">
        <div className="max-w-4xl mx-auto text-center">
          <div className="bg-linear-to-br from-gray-900 to-black rounded-3xl p-12 border border-gray-800 relative overflow-hidden">
            {/* Background Pattern */}
            <div className="absolute top-0 left-0 w-64 h-64 bg-purple-600/5 rounded-full blur-3xl -translate-x-32 -translate-y-32"></div>
            <div className="absolute bottom-0 right-0 w-64 h-64 bg-blue-600/5 rounded-full blur-3xl translate-x-32 translate-y-32"></div>

            <div className="relative z-10">
              <h2 className="text-4xl md:text-5xl font-bold mb-6">
                Ready to Transform Your{" "}
                <span className="text-transparent bg-clip-text bg-linear-to-r from-purple-400 to-pink-400">
                  Fitness Journey?
                </span>
              </h2>

              <p className="text-xl text-gray-400 mb-8 max-w-2xl mx-auto">
                Join thousands of members who have achieved their fitness goals
                with FitAI
              </p>

              <div className="flex flex-col sm:flex-row gap-4 justify-center">
                <Link
                  to="/login"
                  className="group px-8 py-4 bg-linear-to-r from-purple-600 to-pink-600 rounded-xl hover:from-purple-700 hover:to-pink-700 transition-all duration-300 transform hover:scale-[1.02] shadow-lg shadow-purple-500/30 flex items-center justify-center gap-3"
                >
                  <span className="text-lg font-semibold">
                    Get Started Free
                  </span>
                  <ArrowRight className="w-5 h-5 group-hover:translate-x-1 transition-transform" />
                </Link>

                <Link
                  to="/signup"
                  className="px-8 py-4 bg-gray-900 border border-gray-800 rounded-xl hover:bg-gray-800 transition-all duration-300 transform hover:scale-[1.02] flex items-center justify-center gap-3"
                >
                  <span className="text-lg font-semibold">Explore Plans</span>
                  <TrendingUp className="w-5 h-5 text-blue-400" />
                </Link>
              </div>

              <div className="mt-8 flex items-center justify-center gap-2 text-gray-500">
                <CheckCircle className="w-5 h-5 text-green-400" />
                <span>No credit card required • 14-day free trial</span>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t border-gray-800 py-12 px-4">
        <div className="max-w-7xl mx-auto">
          <div className="grid grid-cols-1 md:grid-cols-4 gap-8">
            {/* Brand */}
            <div>
              <div className="flex items-center gap-3 mb-4">
                <div className="p-2 bg-linear-to-r from-purple-600 to-pink-600 rounded-xl">
                  <Dumbbell className="w-6 h-6" />
                </div>
                <h3 className="text-2xl font-bold">
                  Fit
                  <span className="text-transparent bg-clip-text bg-linear-to-r from-purple-400 to-pink-400">
                    AI
                  </span>
                </h3>
              </div>
              <p className="text-gray-400">
                AI-powered fitness platform transforming lives through
                technology and expertise.
              </p>
            </div>

            {/* Quick Links */}
            <div>
              <h4 className="font-bold mb-4">Platform</h4>
              <ul className="space-y-2">
                <li>
                  <Link
                    to="/"
                    className="text-gray-400 hover:text-white transition-colors"
                  >
                    Home
                  </Link>
                </li>
                <li>
                  <Link
                    to="/login"
                    className="text-gray-400 hover:text-white transition-colors"
                  >
                    Login
                  </Link>
                </li>
                <li>
                  <Link
                    to="/signup"
                    className="text-gray-400 hover:text-white transition-colors"
                  >
                    Sign Up
                  </Link>
                </li>
                <li>
                  <Link
                    to="/home"
                    className="text-gray-400 hover:text-white transition-colors"
                  >
                    Dashboard
                  </Link>
                </li>
              </ul>
            </div>

            {/* Features */}
            <div>
              <h4 className="font-bold mb-4">Features</h4>
              <ul className="space-y-2">
                <li className="text-gray-400">AI Workout Plans</li>
                <li className="text-gray-400">Nutrition Tracking</li>
                <li className="text-gray-400">Progress Analytics</li>
                <li className="text-gray-400">Expert Trainers</li>
              </ul>
            </div>

            {/* Contact */}
            <div>
              <h4 className="font-bold mb-4">Contact</h4>
              <ul className="space-y-2">
                <li className="text-gray-400">support@fitai.com</li>
                <li className="text-gray-400">+1 (555) 123-4567</li>
                <li className="text-gray-400">9 AM - 6 PM EST</li>
              </ul>
            </div>
          </div>

          <div className="mt-12 pt-8 border-t border-gray-800 text-center text-gray-500">
            <p>© 2024 FitAI. All rights reserved.</p>
            <p className="mt-2 text-sm">
              AI-Powered Fitness & Nutrition Platform
            </p>
          </div>
        </div>
      </footer>
    </div>
  );
};

export default LandingPage;
